### ISSUE TITLE
Auto-detect IPython pane

### ISSUE THREAD

**Issue by justmytwospence** [julienr/vim-cellmode#1]
Would there be any way for this plugin to scan all current tmux panes and use the one named `ipython`? It could start the search in the current window, then work its way out to other windows and then other sessions.

**Comment by sneilan** [comment]
Yes, that would be cool. Otherwise this plugin doesn't really work.

Also, I don't understand why everything must be in blocks. Why can't I just send a visual selection?

**Comment by julienr** [comment]
@justmytwospence That sounds like a good (and doable) idea. I might work on it at some point in the future (or be happy with any pull request implementing it).

@sneilan If you select some text in visual mode and do ctrl+c, it should send the selection to ipython.

**Comment by julienr** [comment]
The autodetect ipython could be done the following way :
- If the `cellmode_tmux_sessionname` and other target variables are not set
- Run `tmux list-session` and prompt the user to pick a session (defaulting to the first)
- Run `tmux list-windows -t session` and prompt the user to pick a window
- Run `tmux list-panes -t session:window` and prompt the user to pick a pane

**Comment by julienr** [comment]
Commit 20af3284c99 fixes this issue. By default, the target session name and window name are now empty and this lets tmux pick a session automatically. If there is a single running tmux or if you're running vim from inside tmux, this will do the right thing. Otherwise, it'll pick the most recent (I think) session.
