### ISSUE TITLE
Make vim-cellmode compatible with Spyder style cell delimiters

### ISSUE THREAD

**Issue by michaelfsp** [julienr/vim-cellmode#17]
This is a proposal for an enhancement consisting of making vim-cellmode compatible with Spyder style cell delimiters '#%%' and '# %%' (https://pythonhosted.org/spyder/editor.html#how-to-define-a-code-cell).

**Comment by julienr** [comment]
I like it. I'll put that on my TODO list. Or you can do a PR if you feel like it :)

**Comment by julienr** [comment]
I just pushed a change to master that should fix this. 
This adds a `g:cellmode_cell_delimiter` configuration variable that allow you to customize the cell delimiter to use. By default, I configured it to match `##`, `#%%` and `# %%` so it should work with spyder cells.

Can you test and let me know if this solves your problem ? Thanks
