### ISSUE TITLE
Copy made in vim panel and not tmux

### ISSUE THREAD

**Issue by zippeurfou** [julienr/vim-cellmode#20]
So I have vim and tmux.
It looks like that (ipython and vim):
![screen shot 2017-07-19 at 5 52 16 pm](https://user-images.githubusercontent.com/4520383/28391208-0c6ab15e-6cab-11e7-9875-0a1fc43b6d74.png)
and this is my version of vim:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 19 2017 05:09:18)
MacOS X (unix) version
Included patches: 1-647
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.1 -lobjc
```

When I select some text and hit ctrl c. I can see that it tries to execute the command but somehow it paste it inside my vim window instead of my ipython one.
However, `:VimuxPromptCommand` do find the ipython pane.
The only configuration I made in my `.vimrc` is this:
`let g:cellmode_use_tmux=1`
Here is an example of what I am speaking about:
1. Selecting
![screen shot 2017-07-19 at 5 47 56 pm](https://user-images.githubusercontent.com/4520383/28391431-0f3d62ae-6cac-11e7-893a-6b16004a0f0e.png)
2. Ctrl + c
![screen shot 2017-07-19 at 5 48 07 pm](https://user-images.githubusercontent.com/4520383/28391209-0c6b3fe8-6cab-11e7-8798-aaa88b391bd6.png)
(the ipython has nothing).

However, I can see it would work as if I manually type the command in ipython it does work:
![screen shot 2017-07-19 at 5 48 39 pm](https://user-images.githubusercontent.com/4520383/28391210-0c6f9958-6cab-11e7-8b12-a2596fc46c9f.png)

**Comment by julienr** [comment]
So I think this is because cellmode sends the command to pane number 0 by default. And in this case, I guess vim is running in pane 0 (you can check with `prefix + q`in tmux. by default prefix is `ctrl+b`)

You can configure cellmode to target another pane by settings the ``cellmode_tmux_panenumber`` variable. For example ``let g:cellmode_tmux_panenumber=1`` will set it for the current vim instance. Or you can put that line in your .vimrc to persist it.

Let me know if this fixes your problem.

**Comment by zippeurfou** [comment]
Closing it as it works like a charm with `let g:cellmode_tmux_panenumber=1`
Thank you @julienr for the help.

**Comment by julienr** [comment]
Great, glad it works !
