### ISSUE TITLE
%load -y /var..../1.ipy  fg: job not found: load

### ISSUE THREAD

**Issue by mnorayr** [julienr/vim-cellmode#23]
Hi, 
in os x terminal, in tmux second pane that has been both session and window renamed to ipython, 
I get an error 
%load -y /var..../1.ipy  
fg: job not found: load 

Thank you!

**Comment by julienr** [comment]
Do you have ipython running in the ipython tmux window ?

**Comment by mnorayr** [comment]
Hi, I reinstalled and it works now! Thank you very much!
