### ISSUE TITLE
vim-cellmode seems to point to the wrong pane.

### ISSUE THREAD

**Issue by razaLoba** [julienr/vim-cellmode#28]
Hi, 
I have installed this plugin today to vim. I open two tmux panes, one with a .py and the other with ipython. When I execute any of the commands from vim-cellmode, for instance `:call RunTmuxPythonCell(0)`, instead of showing the output on the pane with ipython, it adds the following line to the .py file: 

> ad -y /tmp/nvim9Q0nEt/3.ipy.

I can't figure out what is de issue. I have tried it in both neovim and vim and both using other plugins or as a sigle plugin.
The software versions are:

Vim 8.1
Ubuntu 20.04
Neovim 0.4.3
Ipython 7.18.1
Python 3.7.6

Thanks in advance

Regards

**Comment by razaLoba** [comment]
Hi, 
As thought, it was pointing to the wrong pane. I have solve it adding `let g:cellmode_tmux_panenumber=1` to the file init.vim

**Comment by julienr** [comment]
Thanks for the report and finding the solution !
