### ISSUE TITLE
make paste-files unique per paste

### ISSUE THREAD

**Issue by nilsbecker** [julienr/vim-cellmode#5]
hi, i'm using vim-cellmode since it's the only working solution i found to send longer inputs to ipython. (except vim-ipython which does too much) the one thing that is not working now is to send multiple cells in rapid succession, ie. send the next one before ipython handles the previous one. since the temporary file is always the same, in this way, intermediate cells get skipped as the file is overwritten in the meantime.

it would be great of there was something like a rolling buffer of numbered temporary files. ie. keep always at most n files around, and overwrite only the oldest one on each send. maybe n=20 or so pending cells should suffice. probably n=5 is enough most of the time.

**Comment by julienr** [comment]
This is a good idea. `n` should be user configurable with some reasonable default.

It would be nice if we could clean those temporary files. We could do that when we close the file, but I'm not sure how to register for that event in vimscript.

**Comment by nilsbecker** [comment]
i tested and it works fine. it's really speeding up my work, thanks!
