### ISSUE TITLE
make it possible to have buffer-local targets

### ISSUE THREAD

**Issue by nilsbecker** [julienr/vim-cellmode#8]
it happens now and then that i have two buffers that i would like to send cells to different ipython kernels/tmux panes from. it seems to be impossible to set the tmux targets per buffer (right?) that could be handy to have, if it does not make configuration too complicated for the simple use case...

**Comment by julienr** [comment]
You should be able to define buffer-scoped variable (they override globals) :

```
let b:tmux_sessionname='ipython'
let b:tmux_windowname='another-ipython'
let b:tmux_panenumber='1'
```

If I open two tmux panes, launch one ipython in each and then set one vim buffer to send to pane 0 and another to pane 1, this works for me.

I agree this isn't well documented and thank you for opening issue #7 that I will have to work on :)

**Comment by nilsbecker** [comment]
ok, cool, thanks

**Comment by nilsbecker** [comment]
actually, it seems to work differently. for me, it is always the tmux pane that was last active (last received input) which responds to what is sent from vim. the variables do not seem to matter (much/at all) ? i got used to it, it's workable. but still unexpected...

**Comment by julienr** [comment]
This is really strange, it is working as expected on my system (OSX, tmux 2.0).

Can you try the following :
- Open tmux, rename session and window to ipython and then create two panes
- Run the following

```
$ tmux set-buff "test"
$ tmux paste-buffer -t ipython:ipython.0
$ tmux paste-buffer -t ipython:ipython.1
```

This should print 'test' once in pane 0 and once in pane 1. (Those are the same commands used by vim-cellmod under the hood)

**Comment by nilsbecker** [comment]
sorry for not following up, this somehow escaped my attention. when i do what you describe i do see what you expect. 'test' first in pane 0 then in pane 1.

but: i think i was confused about what tmux panes are. i think i did not have different actual tmux panes but different sessions or different windows. i'm still confused by the terminology. is there a hierarchy session/window/pane in tmux?

**Comment by nilsbecker** [comment]
so i tried what you described in the post from 12 jun 15. i have to windows open in vim, with different buffers. i define the local variables 

```
let b:tmux_sessionname='ipython'
let b:tmux_windowname='ipython'
let b:tmux_panenumber='1'
```

(and pane 0 in the other window). i then send selected regions from each window. both then appear in the pane 0 of my tmux session.

**Comment by julienr** [comment]
The variable names are now prefixed with `cellmode` to avoid confusion (see 80807c570e), try with

```
let b:cellmode_tmux_sessionname='ipython'
let b:cellmode_tmux_windowname='ipython'
let b:cellmode_tmux_panenumber='1'
```
